---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 1h
  url: https://nextcloud.github.io/helm/
  timeout: 60s
