apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  driftDetection:
    mode: enabled
  interval: 1h
  chart:
    spec:
      chart: immich
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    immich:
      persistence:
        library:
          existingClaim: nfs-personal-pvc

    server:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-server
        pullPolicy: IfNotPresent
      env:
        TZ: America/Chicago
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: proxmox-host
                    operator: In
                    values:
                      - pve1

    machine-learning:
      enabled: false

    postgresql:
      enabled: false
      global:
        postgresql:
          auth:
            username: immich
            password: immich
            database: immich

    redis:
      enabled: false
