apiVersion: v1
kind: Secret
metadata:
    name: immich-db-credentials
    namespace: immich
stringData:
    password: ENC[AES256_GCM,data:FEuY1ho/0A+u6z2uKvNAgscsrYnrTottsIHjIfdJwPo=,iv:r7zNijJ+lEMEIHDaSlaYOoiL8N/YKPf43T4SkdBHBPE=,tag:nvUvvSav/Hshfsfsto3DlA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQkQxdGpQQzJ5L2VsTVIx
            b1h1eXNoOWdDakJ6TWxYNUcxbmxNZGlXVmtNCnZaOUZLRmlLQVRDY2NjQTJWb3VQ
            UDdBazBzRUZFbGJYMU9qTEZPekRPek0KLS0tIDQrWmQxeWtQQWkzdFhNQTI2N3dh
            b3hPcStJb3owRkUwL2FiT2YzNjZpNU0KpYkljK2CYBdjf5tJhYGwgHWZVuce0YhW
            UPIVZye/XXNM9VdVMu5f7nor7njZqG6xO0VBijD8i25dJcwatFsNaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18pv5qtszkd9f4yvkrrm530kj38f34jqdum0wtltaudadns6d9yksxuaetq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T05:02:10Z"
    mac: ENC[AES256_GCM,data:2mO4HBj7SuzWCluXBqdLRQLYIfNCInnizaGMaI75/OdFycFQAG1157Ptmh931FO7fM750OOTCQeDnCALlbaQoxH76XpRta0+phWZ0jJS+69FiTTI5wkNE5AaaL/dpeujgMIuvLr7DU+FSzAwyUgpKweYihuH7CNCIQqIDH93fhw=,iv:aTFvX9grmjSehBvVPaAAWir/AvXXeLW5mDsNbz28fzc=,tag:i7r3VoEwf1+/p8Z6NWMuJw==,type:str]
    version: 3.13.1
