apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 1h
  chart:
    spec:
      chart: nextcloud
      version: 4.5.12
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    nextcloud:
      host: nextcloud.totorolab.local
    ingress:
      enabled: true
      className: traefik
    persistence:
      enabled: true
      existingClaim: ""
      size: 5Gi
