apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: totorolab-ca
  namespace: cert-manager
spec:
  isCA: true
  secretName: totorolab-ca
  commonName: totorolab-ca
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: totorolab-ca
spec:
  ca:
    secretName: totorolab-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring
spec:
  secretName: grafana-cert
  issuerRef:
    name: totorolab-ca
    kind: ClusterIssuer
  dnsNames:
    - grafana.totorolab.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-cert
  namespace: nextcloud
spec:
  secretName: nextcloud-cert
  issuerRef:
    name: totorolab-ca
    kind: ClusterIssuer
  dnsNames:
    - nextcloud.totorolab.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  namespace: traefik
spec:
  secretName: traefik-cert
  issuerRef:
    name: totorolab-ca
    kind: ClusterIssuer
  dnsNames:
    - totorolab.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homarr-cert
  namespace: homarr
spec:
  secretName: homarr-cert
  issuerRef:
    name: totorolab-ca
    kind: ClusterIssuer
  dnsNames:
    - homarr.totorolab.local
